import { Roboto, Open_Sans } from "next/font/google";
import "./globals.scss";
import Header from "@/components/Global/Header/Header";
import Footer from "@/components/Global/Footer/Footer";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });
const openSans = Open_Sans({ subsets: ["latin"], weight: ["400", "600"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} ${openSans.className}`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
