import Head from 'next/head';
import Header from '../components/globals/header/Header';
import Home_top from '../components/home_top_banner/Home_top';
import Product_category from '../components/product_category/Product_category';

export default function Home() {
  return (
    <>
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <Header />
       <Home_top />
       <Product_category />
      </>
  )
}
